apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myservice.name" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "myservice.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replica | default 1 }}
  selector:
    matchLabels:
      {{- include "myservice.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "myservice.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ include "myservice.name" . }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: IfNotPresent
          resources: {}
